// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStudent = "student"

// Student mapped from table <student>
type Student struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Sex  string `gorm:"column:sex" json:"sex"`
	Age  int32  `gorm:"column:age" json:"age"`
}

// TableName Student's table name
func (*Student) TableName() string {
	return TableNameStudent
}
