// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMedicalExaminationAppointmentInfo = "medical_examination_appointment_info"

// MedicalExaminationAppointmentInfo 体检预约单信息
type MedicalExaminationAppointmentInfo struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增id" json:"id"`                        // 自增id
	AppointState    int32     `gorm:"column:appoint_state;not null;comment:体检预约单状态 -1预约失败 0接收预约 4客户取消" json:"appoint_state"` // 体检预约单状态 -1预约失败 0接收预约 4客户取消
	MedExamSchID    int64     `gorm:"column:med_exam_sch_id;not null;comment:体检排班id" json:"med_exam_sch_id"`                 // 体检排班id
	SchDate         string    `gorm:"column:sch_date;not null;comment:体检日期" json:"sch_date"`                                 // 体检日期
	UserID          int64     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                                   // 用户id
	VisitID         int64     `gorm:"column:visit_id;not null;comment:体检人id" json:"visit_id"`                                // 体检人id
	HospitalID      int64     `gorm:"column:hospital_id;not null;comment:医院Id" json:"hospital_id"`                           // 医院Id
	HospitalName    string    `gorm:"column:hospital_name;comment:医院名称(冗)" json:"hospital_name"`                             // 医院名称(冗)
	MedExamType     int32     `gorm:"column:med_exam_type;not null;comment:体检类型 1入职体检 2驾驶员体检 3居住证体检" json:"med_exam_type"`   // 体检类型 1入职体检 2驾驶员体检 3居住证体检
	RealName        string    `gorm:"column:real_name;not null;comment:体检人姓名" json:"real_name"`                              // 体检人姓名
	IDType          int32     `gorm:"column:id_type;not null;comment:体检人证件类型(身份证，通行证，军人证，等)" json:"id_type"`                 // 体检人证件类型(身份证，通行证，军人证，等)
	IDCardNo        string    `gorm:"column:id_card_no;not null;comment:体检人证件号" json:"id_card_no"`                           // 体检人证件号
	Sex             int32     `gorm:"column:sex;not null;comment:体检人性别 1：男 0：女" json:"sex"`                                  // 体检人性别 1：男 0：女
	Mobile          string    `gorm:"column:mobile;not null;comment:体检人手机号" json:"mobile"`                                   // 体检人手机号
	MedicalCardType string    `gorm:"column:medical_card_type;default:1;comment:体检人就诊卡类别" json:"medical_card_type"`          // 体检人就诊卡类别
	MedicalCardNo   string    `gorm:"column:medical_card_no;comment:体检人就诊卡号" json:"medical_card_no"`                         // 体检人就诊卡号
	AdminRemark     string    `gorm:"column:admin_remark;comment:后台手工备注" json:"admin_remark"`                                // 后台手工备注
	CreateAt        time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"`              // 创建时间
	UpdateAt        time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;comment:修改时间" json:"update_at"`              // 修改时间
	CreateUserID    int64     `gorm:"column:create_user_id;comment:创建人id" json:"create_user_id"`                             // 创建人id
	UpdateUserID    int64     `gorm:"column:update_user_id;comment:修改人id" json:"update_user_id"`                             // 修改人id
	OrderNum        int32     `gorm:"column:order_num;default:1;comment:序号" json:"order_num"`                                // 序号
	Version         int32     `gorm:"column:version;default:1;comment:乐观锁号" json:"version"`                                  // 乐观锁号
	AppKey          string    `gorm:"column:app_key;default:edc;comment:应用key" json:"app_key"`                               // 应用key
	DeleteFlag      []uint8   `gorm:"column:delete_flag;default:b'0;comment:逻辑删除" json:"delete_flag"`                        // 逻辑删除
	UUID            string    `gorm:"column:uuid;comment:uuid" json:"uuid"`                                                  // uuid
	Status          int32     `gorm:"column:status;default:1;comment:业务状态，草稿，正常，禁用" json:"status"`                           // 业务状态，草稿，正常，禁用
	DraftData       string    `gorm:"column:draft_data;comment:草稿" json:"draft_data"`                                        // 草稿
	ProjectID       int64     `gorm:"column:project_id;comment:项目id" json:"project_id"`                                      // 项目id
	Tags            string    `gorm:"column:tags;comment:标签" json:"tags"`                                                    // 标签
	ZyID            string    `gorm:"column:zy_id" json:"zy_id"`
}

// TableName MedicalExaminationAppointmentInfo's table name
func (*MedicalExaminationAppointmentInfo) TableName() string {
	return TableNameMedicalExaminationAppointmentInfo
}
