// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSqlTest = "sql_test"

// SqlTest mapped from table <sql_test>
type SqlTest struct {
	ID   int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"` // id
	Name string `gorm:"column:name;comment:姓名" json:"name"`                           // 姓名
	Age  int32  `gorm:"column:age;comment:年龄" json:"age"`                             // 年龄
}

// TableName SqlTest's table name
func (*SqlTest) TableName() string {
	return TableNameSqlTest
}
