// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUserAppointmentInfo = "user_appointment_info"

// UserAppointmentInfo 用户预约表
type UserAppointmentInfo struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`                                       // id
	VisitID           int64     `gorm:"column:visit_id;comment:就诊人id" json:"visit_id"`                                                      // 就诊人id
	DrID              int64     `gorm:"column:dr_id;not null;comment:医生id" json:"dr_id"`                                                    // 医生id
	DrSchID           int64     `gorm:"column:dr_sch_id;not null;comment:医生排班id" json:"dr_sch_id"`                                          // 医生排班id
	HosID             int64     `gorm:"column:hos_id;not null;comment:医院id" json:"hos_id"`                                                  // 医院id
	PriDeptID         int64     `gorm:"column:pri_dept_id;not null;comment:主科室id" json:"pri_dept_id"`                                       // 主科室id
	SecDeptID         int64     `gorm:"column:sec_dept_id;not null;comment:科室id" json:"sec_dept_id"`                                        // 科室id
	SchType           int32     `gorm:"column:sch_type;not null;comment:排班类型" json:"sch_type"`                                              // 排班类型
	SchDate           time.Time `gorm:"column:sch_date;not null;comment:就诊日期" json:"sch_date"`                                              // 就诊日期
	StartTime         string    `gorm:"column:start_time;comment:开始时间" json:"start_time"`                                                   // 开始时间
	EndTime           string    `gorm:"column:end_time;comment:结束时间" json:"end_time"`                                                       // 结束时间
	BookingNo         string    `gorm:"column:booking_no;comment:接口医院预约编号" json:"booking_no"`                                               // 接口医院预约编号
	BookingSeq        string    `gorm:"column:booking_seq;comment:接口医院顺序号" json:"booking_seq"`                                              // 接口医院顺序号
	PayPrice          int32     `gorm:"column:pay_price;comment:价格(分)" json:"pay_price"`                                                    // 价格(分)
	AppointState      int32     `gorm:"column:appoint_state;not null;comment:接口返回状态 0待返回 1成功收到返回 2补发确认预约成功 3补发确认预约失败" json:"appoint_state"` // 接口返回状态 0待返回 1成功收到返回 2补发确认预约成功 3补发确认预约失败
	IsNotice          []uint8   `gorm:"column:is_notice;comment:是否通知" json:"is_notice"`                                                     // 是否通知
	NoticeState       int32     `gorm:"column:notice_state;comment:通知状态" json:"notice_state"`                                               // 通知状态
	PayStatus         string    `gorm:"column:pay_status;comment:支付状态：已支付-PAYED，未支付-UNPAY，无需支付-NOPAY" json:"pay_status"`                    // 支付状态：已支付-PAYED，未支付-UNPAY，无需支付-NOPAY
	PayTime           time.Time `gorm:"column:pay_time;comment:支付时间" json:"pay_time"`                                                       // 支付时间
	AdminRemark       string    `gorm:"column:admin_remark;comment:后台手工备注" json:"admin_remark"`                                             // 后台手工备注
	SourceID          int64     `gorm:"column:source_id;comment:号源id" json:"source_id"`                                                     // 号源id
	MedicalCardType   string    `gorm:"column:medical_card_type;comment:就诊卡类别" json:"medical_card_type"`                                    // 就诊卡类别
	MedicalCardNo     string    `gorm:"column:medical_card_no;comment:就诊卡号" json:"medical_card_no"`                                         // 就诊卡号
	PayType           string    `gorm:"column:pay_type;comment:支付类型" json:"pay_type"`                                                       // 支付类型
	ChannelID         int64     `gorm:"column:channel_id;comment:渠道id" json:"channel_id"`                                                   // 渠道id
	UserID            int64     `gorm:"column:user_id;comment:用户id" json:"user_id"`                                                         // 用户id
	OpenID            string    `gorm:"column:open_id;comment:第三方OpenId" json:"open_id"`                                                    // 第三方OpenId
	IsHandle          []uint8   `gorm:"column:is_handle;comment:是否处理（非接口给医院）" json:"is_handle"`                                             // 是否处理（非接口给医院）
	IsConfirmed       []uint8   `gorm:"column:is_confirmed;comment:第三方是否已确认此订单" json:"is_confirmed"`                                        // 第三方是否已确认此订单
	CancelType        string    `gorm:"column:cancel_type;comment:取消类型" json:"cancel_type"`                                                 // 取消类型
	CancelReason      string    `gorm:"column:cancel_reason;comment:取消原因" json:"cancel_reason"`                                             // 取消原因
	AppointCode       string    `gorm:"column:appoint_code;comment:预约码" json:"appoint_code"`                                                // 预约码
	IfScheNo          string    `gorm:"column:if_sche_no;comment:接口医院排班编号" json:"if_sche_no"`                                               // 接口医院排班编号
	VisitType         int32     `gorm:"column:visit_type;comment:初复诊（初诊1，复诊2）" json:"visit_type"`                                           // 初复诊（初诊1，复诊2）
	IfHospitalData    string    `gorm:"column:if_hospital_data;comment:接口医院相关数据（科室，医生的医院编码）" json:"if_hospital_data"`                       // 接口医院相关数据（科室，医生的医院编码）
	VisitSnapshot     string    `gorm:"column:visit_snapshot;comment:就诊人快照" json:"visit_snapshot"`                                          // 就诊人快照
	DrSchInfoSnapshot string    `gorm:"column:dr_sch_info_snapshot;comment:医生排班快照" json:"dr_sch_info_snapshot"`                             // 医生排班快照
	IsIfHospital      []uint8   `gorm:"column:is_if_hospital;comment:是否接口医院（冗）" json:"is_if_hospital"`                                      // 是否接口医院（冗）
	IDCardNum         string    `gorm:"column:id_card_num;comment:身份证号（冗）" json:"id_card_num"`                                              // 身份证号（冗）
	VisitName         string    `gorm:"column:visit_name;comment:就诊人姓名(冗)" json:"visit_name"`                                               // 就诊人姓名(冗)
	VisitMobile       string    `gorm:"column:visit_mobile;comment:就诊人手机号(冗)" json:"visit_mobile"`                                          // 就诊人手机号(冗)
	HospitalName      string    `gorm:"column:hospital_name;comment:医院名称(冗)" json:"hospital_name"`                                          // 医院名称(冗)
	DeptName          string    `gorm:"column:dept_name;comment:科室名称(冗)" json:"dept_name"`                                                  // 科室名称(冗)
	DoctorName        string    `gorm:"column:doctor_name;comment:医生姓名(冗)" json:"doctor_name"`                                              // 医生姓名(冗)
	IsRescheduled     []uint8   `gorm:"column:is_rescheduled;not null;default:b'0;comment:是否改期（默认否）" json:"is_rescheduled"`                 // 是否改期（默认否）
	ApptExtendsJSON   string    `gorm:"column:appt_extends_json;comment:预约扩展信息json" json:"appt_extends_json"`                               // 预约扩展信息json
	ChannelCode       string    `gorm:"column:channel_code;comment:渠道编码" json:"channel_code"`                                               // 渠道编码
	ChannelOrderNo    string    `gorm:"column:channel_order_no;comment:渠道订单号" json:"channel_order_no"`                                      // 渠道订单号
	CreateAt          time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"`                           // 创建时间
	UpdateAt          time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;comment:修改时间" json:"update_at"`                           // 修改时间
	CreateUserID      int64     `gorm:"column:create_user_id;comment:创建人id" json:"create_user_id"`                                          // 创建人id
	UpdateUserID      int64     `gorm:"column:update_user_id;comment:修改人id" json:"update_user_id"`                                          // 修改人id
	OrderNum          int32     `gorm:"column:order_num;default:1;comment:序号" json:"order_num"`                                             // 序号
	Version           int32     `gorm:"column:version;default:1;comment:乐观锁号" json:"version"`                                               // 乐观锁号
	AppKey            string    `gorm:"column:app_key;default:edc;comment:应用key" json:"app_key"`                                            // 应用key
	DeleteFlag        []uint8   `gorm:"column:delete_flag;default:b'0;comment:逻辑删除" json:"delete_flag"`                                     // 逻辑删除
	UUID              string    `gorm:"column:uuid;comment:uuid" json:"uuid"`                                                               // uuid
	Status            int32     `gorm:"column:status;default:1;comment:业务状态，草稿，正常，禁用" json:"status"`                                        // 业务状态，草稿，正常，禁用
	DraftData         string    `gorm:"column:draft_data;comment:草稿" json:"draft_data"`                                                     // 草稿
	ProjectID         int64     `gorm:"column:project_id;comment:项目id" json:"project_id"`                                                   // 项目id
	Tags              string    `gorm:"column:tags;comment:标签" json:"tags"`                                                                 // 标签
	ZyID              string    `gorm:"column:zy_id;comment:助医网id" json:"zy_id"`                                                            // 助医网id
}

// TableName UserAppointmentInfo's table name
func (*UserAppointmentInfo) TableName() string {
	return TableNameUserAppointmentInfo
}
