server:
  port: 9090
datasource:
  driverName: mysql
  host: 74.48.19.200
  port: 33306
  database: sql_test
  username: root
  password: Lyh150098!@#
  charset: utf8mb4
redis:
  host: 74.48.19.200
  port: 63790
  password: Lyh150098!@#
  database: 0
  timeout: 10000ms
