// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHospitalDeptInfo = "hospital_dept_info"

// HospitalDeptInfo 医院科室信息
type HospitalDeptInfo struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`             // id
	GlobalDeptCode  string    `gorm:"column:global_dept_code;comment:全局科室代码" json:"global_dept_code"`           // 全局科室代码
	HosID           int64     `gorm:"column:hos_id;comment:医院id" json:"hos_id"`                                 // 医院id
	ParentID        int64     `gorm:"column:parent_id;comment:上级科室id(一级0)" json:"parent_id"`                    // 上级科室id(一级0)
	DeptName        string    `gorm:"column:dept_name;comment:科室名称" json:"dept_name"`                           // 科室名称
	DeptCode        string    `gorm:"column:dept_code;comment:科室代码" json:"dept_code"`                           // 科室代码
	DeptDescription string    `gorm:"column:dept_description;comment:科室描述" json:"dept_description"`             // 科室描述
	IsImportant     []uint8   `gorm:"column:is_important;comment:重点科室" json:"is_important"`                     // 重点科室
	IsHot           []uint8   `gorm:"column:is_hot;comment:热门" json:"is_hot"`                                   // 热门
	CreateAt        time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_at"` // 创建时间
	UpdateAt        time.Time `gorm:"column:update_at;default:CURRENT_TIMESTAMP;comment:修改时间" json:"update_at"` // 修改时间
	CreateUserID    int64     `gorm:"column:create_user_id;comment:创建人id" json:"create_user_id"`                // 创建人id
	UpdateUserID    int64     `gorm:"column:update_user_id;comment:修改人id" json:"update_user_id"`                // 修改人id
	OrderNum        int32     `gorm:"column:order_num;default:1;comment:序号" json:"order_num"`                   // 序号
	Version         int32     `gorm:"column:version;default:1;comment:乐观锁号" json:"version"`                     // 乐观锁号
	AppKey          string    `gorm:"column:app_key;default:edc;comment:应用key" json:"app_key"`                  // 应用key
	DeleteFlag      []uint8   `gorm:"column:delete_flag;default:b'0;comment:逻辑删除" json:"delete_flag"`           // 逻辑删除
	UUID            string    `gorm:"column:uuid;comment:uuid" json:"uuid"`                                     // uuid
	Status          int32     `gorm:"column:status;default:1;comment:业务状态，草稿，正常，禁用" json:"status"`              // 业务状态，草稿，正常，禁用
	DraftData       string    `gorm:"column:draft_data;comment:草稿" json:"draft_data"`                           // 草稿
	ProjectID       int64     `gorm:"column:project_id;comment:项目id" json:"project_id"`                         // 项目id
	Tags            string    `gorm:"column:tags;comment:标签" json:"tags"`                                       // 标签
	ZyID            string    `gorm:"column:zy_id" json:"zy_id"`
}

// TableName HospitalDeptInfo's table name
func (*HospitalDeptInfo) TableName() string {
	return TableNameHospitalDeptInfo
}
